#include "audio_plugin.h"

#include "source/PluginProcessor.cpp"
#include "source/PluginEditor.cpp"

// #include all additional .cpp files below
#include "source/gui/OpnaLookAndFeel.cpp"
#include "source/gui/OpnaModalBase.cpp"
#include "source/gui/OpnaModal.cpp"
#include "source/gui/SampleImportDialog.cpp"
#include "source/gui/SettingsDialog.cpp"
#include "source/gui/FmDisplays.cpp"
#include "source/gui/FmLfoBox.cpp"
#include "source/gui/FmAlgoPanel.cpp"
#include "source/gui/RoutingMatrix.cpp"
#include "source/gui/Ch3SpecialPanel.cpp"
#include "source/gui/FmPartPanel.cpp"
#include "source/gui/FmPage.cpp"
#include "source/gui/SsgAdpcmPage.cpp"
#include "source/gui/GlobalPage.cpp"
#include "source/PatchParameters.cpp"
#include "source/Presets.cpp"
#include "source/FactoryPresets.cpp"
#include "source/PresetManager.cpp"
#include "source/RhythmParameters.cpp"
#include "source/SamplerParameters.cpp"
#include "source/SsgParameters.cpp"
#include "source/voice/AdpcmBEncoder.cpp"
#include "source/voice/AdpcmBRegisterEncoder.cpp"
#include "source/voice/Ch3SpecialEncoder.cpp"
#include "source/voice/Ch3SpecialPart.cpp"
#include "source/voice/RegisterEncoder.cpp"
#include "source/voice/RhythmRegisterEncoder.cpp"
#include "source/voice/SsgRegisterEncoder.cpp"
#include "source/voice/VoiceAllocator.cpp"
